const images = {
  hero: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=80",
  cappadocia: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?auto=format&fit=crop&w=1200&q=80",
  italy: "https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1200&q=80",
  blacksea: "https://images.unsplash.com/photo-1621807416846-e67305ed63d5?auto=format&fit=crop&w=1200&q=80",
  balkans: "https://images.unsplash.com/photo-1574950578143-858c6fc58922?auto=format&fit=crop&w=1200&q=80",
  aegean: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
  paris: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
  amsterdam: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=900&q=80",
  santorini: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80",
  barcelona: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=900&q=80",
  about: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1400&q=80",
  blog: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1400&q=80",
  luggage: "https://images.unsplash.com/photo-1553531384-cc64ac80f931?auto=format&fit=crop&w=1000&q=80",
  papers: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1000&q=80",
  food: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?auto=format&fit=crop&w=1000&q=80",
};

const commonTourDetails = {
  tr: {
    included: ["Profesyonel rehberlik", "Programdaki şehir ve bölge gezileri", "Konforlu ulaşım", "Seçili otellerde konaklama", "7/24 operasyon desteği"],
    excluded: ["Kişisel harcamalar", "Müze ve ören yeri girişleri", "Program dışı yemekler", "Vize ve sigorta ücretleri"],
    accommodation: ["Merkezi veya rotaya uygun oteller", "Kahvaltı dahil konaklama", "Temiz, güvenilir ve misafir puanı yüksek tesisler"],
    transport: ["Rota yapısına uygun uçak veya otobüs ulaşımı", "Program içi transferler", "Deneyimli sürücülerle güvenli yolculuk"],
    documents: ["Kimlik veya geçerli pasaport", "Yurt dışı turlarda gerekli vize", "Seyahat sigortası önerilir"],
    cancellation: "Kalkıştan 30 gün öncesine kadar yapılan iptal taleplerinde tedarikçi koşulları ve operasyon giderleri dikkate alınır. Her talep ekibimiz tarafından şeffaf biçimde değerlendirilir.",
  },
  en: {
    included: ["Professional guidance", "Scheduled city and regional visits", "Comfortable transportation", "Accommodation in selected hotels", "24/7 operations support"],
    excluded: ["Personal expenses", "Museum and site entrance fees", "Meals outside the program", "Visa and insurance fees"],
    accommodation: ["Hotels suitable for the route or central locations", "Breakfast included stays", "Clean, trusted properties with strong guest scores"],
    transport: ["Flights or coach travel according to the route", "Transfers within the program", "Safe travel with experienced drivers"],
    documents: ["ID card or valid passport", "Required visa for international tours", "Travel insurance is recommended"],
    cancellation: "Cancellation requests up to 30 days before departure are reviewed according to supplier terms and operational costs. Our team handles every request transparently.",
  },
  ar: {
    included: ["إرشاد احترافي", "جولات المدن والمناطق ضمن البرنامج", "مواصلات مريحة", "إقامة في فنادق مختارة", "دعم تشغيلي على مدار الساعة"],
    excluded: ["المصاريف الشخصية", "رسوم دخول المتاحف والمواقع", "الوجبات خارج البرنامج", "رسوم التأشيرة والتأمين"],
    accommodation: ["فنادق مركزية أو مناسبة للمسار", "إقامة تشمل الإفطار", "منشآت موثوقة ونظيفة وذات تقييم جيد"],
    transport: ["رحلات جوية أو حافلات حسب طبيعة المسار", "تنقلات داخل البرنامج", "رحلة آمنة مع سائقين ذوي خبرة"],
    documents: ["بطاقة هوية أو جواز سفر ساري", "التأشيرة المطلوبة للرحلات الدولية", "ينصح بتأمين السفر"],
    cancellation: "تتم دراسة طلبات الإلغاء حتى 30 يوما قبل الانطلاق وفق شروط الموردين وتكاليف التشغيل، مع توضيح كامل من فريقنا.",
  },
};

export const dictionary = {
  tr: {
    langLabel: "TR",
    dir: "ltr",
    nav: ["Ana Sayfa", "Turlar", "Hakkımızda", "Blog", "SSS", "İletişim"],
    reserve: "Rezervasyon Talebi",
    discoverTours: "Turları Keşfet",
    details: "Detayları Gör",
    continue: "Devamını Oku",
    all: "Tümü",
    filters: "Filtreler",
    search: "Tur, şehir veya kategori ara",
    listed: "tur listeleniyor",
    popularTours: "Popüler Turlar",
    popularTitle: "En çok tercih edilen rotalar",
    popularText: "Planı hazır, rehberi güçlü ve her detayı düşünülmüş turları inceleyin.",
    why: "Neden RotaNova?",
    whyTitle: "Yolculuk boyunca yanınızdayız",
    destinations: "Destinasyonlar",
    destinationTitle: "Rotanıza ilham verecek şehirler",
    how: "Nasıl Çalışır?",
    howTitle: "Üç adımda yola çıkın",
    testimonials: "Misafirlerimiz",
    testimonialsTitle: "Güvenin en güzel hali: gerçek deneyimler",
    blog: "Blog",
    blogTitle: "Seyahate hazırlık rehberleri",
    ctaTitle: "Bir sonraki yolculuğun burada başlıyor.",
    ctaText: "Sana en uygun turu birlikte planlayalım.",
    contactNow: "Hemen İletişime Geç",
    heroTitle: "Hayalindeki rotaya güvenle çık.",
    heroText: "RotaNova Travel ile kültürden doğaya, Avrupa şehirlerinden egzotik destinasyonlara kadar unutulmaz turları keşfet.",
    heroTrust: "TÜRSAB üyesi placeholder · Güvenli ödeme",
    stats: ["10+ yıllık deneyim", "50+ rota", "12.000+ mutlu misafir", "Profesyonel rehberler"],
    whyCards: ["Profesyonel rehberlik", "Güvenli ulaşım", "Özenle seçilmiş oteller", "Küçük grup avantajı", "7/24 destek", "Esnek ödeme seçenekleri"],
    whyCardText: "Seyahatinizin her aşamasında net iletişim, güvenli planlama ve özenli operasyon.",
    steps: ["Rotanı seç", "Rezervasyon talebi gönder", "Valizini hazırla"],
    stepText: "Ekibimiz seçenekleri netleştirir, sizin için en doğru programı birlikte tamamlarız.",
    pageToursText: "Hayalinizdeki yolculuğu filtreleyin, rotaları karşılaştırın ve size en uygun tur için talep bırakın.",
    pageAboutText: "RotaNova Travel, seyahati planlı, güvenli ve ilham verici bir deneyime dönüştürmek için kuruldu.",
    pageBlogText: "Yolculuğa çıkmadan önce işinize yarayacak pratik, sade ve güncel rehberler.",
    pageContactText: "Sorularınızı, tur taleplerinizi ve özel grup planlarınızı bize iletin.",
    pageReservationText: "Birkaç bilgiyi paylaşın, ekibimiz size en uygun program ve ödeme seçenekleriyle dönüş yapsın.",
    pageFaqText: "Rezervasyon, ödeme, vize ve tur süreçleriyle ilgili en çok merak edilenleri yanıtladık.",
    tourSummary: "Tur Özeti",
    itinerary: "Gün Gün Program",
    included: "Fiyata Dahil Olanlar",
    excluded: "Fiyata Dahil Olmayanlar",
    accommodation: "Konaklama Bilgileri",
    transport: "Ulaşım Bilgileri",
    documents: "Gerekli Belgeler",
    cancellation: "İptal ve İade Koşulları",
    similarTours: "Benzer Turlar",
    duration: "Süre",
    route: "Rota",
    startingPrice: "Başlangıç fiyatı",
    departures: "Kalkış tarihleri",
    priceNote: "Kişi başı çift kişilik odada konaklama baz alınmıştır.",
    form: {
      name: "Ad Soyad",
      email: "E-posta",
      phone: "Telefon",
      tour: "İlgilenilen tur",
      guests: "Kişi sayısı",
      date: "Tercih edilen tarih",
      notes: "Ek notlar",
      notesPlaceholder: "Oda tercihi, özel istekler veya merak ettikleriniz",
      kvkk: "KVKK kapsamında kişisel verilerimin iletişim amacıyla işlenmesini kabul ediyorum.",
      submit: "Gönder",
      loading: "Gönderiliyor...",
      success: "Rezervasyon talebiniz başarıyla alındı. Ekibimiz en kısa sürede sizinle iletişime geçecektir.",
      chooseTour: "Tur seçin",
      requiredName: "Ad soyad zorunlu.",
      requiredEmail: "Geçerli e-posta girin.",
      requiredPhone: "Geçerli telefon girin.",
      requiredTour: "Tur seçin.",
      requiredGuests: "Kişi sayısı girin.",
      requiredDate: "Tarih seçin.",
      requiredKvkk: "KVKK onayı gerekli.",
    },
  },
  en: {
    langLabel: "EN",
    dir: "ltr",
    nav: ["Home", "Tours", "About", "Blog", "FAQ", "Contact"],
    reserve: "Reservation Request",
    discoverTours: "Explore Tours",
    details: "View Details",
    continue: "Read More",
    all: "All",
    filters: "Filters",
    search: "Search tour, city or category",
    listed: "tours listed",
    popularTours: "Popular Tours",
    popularTitle: "Most loved routes",
    popularText: "Explore well-planned tours with strong guides and carefully designed details.",
    why: "Why RotaNova?",
    whyTitle: "We are with you throughout the journey",
    destinations: "Destinations",
    destinationTitle: "Cities that inspire your route",
    how: "How It Works",
    howTitle: "Travel in three simple steps",
    testimonials: "Guest Reviews",
    testimonialsTitle: "Real stories from happy travelers",
    blog: "Blog",
    blogTitle: "Travel preparation guides",
    ctaTitle: "Your next journey starts here.",
    ctaText: "Let us plan the best tour for you together.",
    contactNow: "Contact Us Now",
    heroTitle: "Travel your dream route with confidence.",
    heroText: "Discover unforgettable tours with RotaNova Travel, from culture and nature to European cities and exotic destinations.",
    heroTrust: "TURSAB member placeholder · Secure payment",
    stats: ["10+ years of experience", "50+ routes", "12,000+ happy guests", "Professional guides"],
    whyCards: ["Professional guidance", "Safe transportation", "Carefully selected hotels", "Small group advantage", "24/7 support", "Flexible payment options"],
    whyCardText: "Clear communication, safe planning and careful operations at every step of your trip.",
    steps: ["Choose your route", "Send a reservation request", "Pack your suitcase"],
    stepText: "Our team clarifies options and completes the right program together with you.",
    pageToursText: "Filter your dream journey, compare routes and request the tour that fits you best.",
    pageAboutText: "RotaNova Travel was founded to turn travel into a planned, safe and inspiring experience.",
    pageBlogText: "Practical, clear and useful guides before you set off.",
    pageContactText: "Send us your questions, tour requests and private group plans.",
    pageReservationText: "Share a few details and our team will return with the right program and payment options.",
    pageFaqText: "Answers to common questions about reservation, payment, visa and tour processes.",
    tourSummary: "Tour Summary",
    itinerary: "Day by Day Program",
    included: "Included",
    excluded: "Not Included",
    accommodation: "Accommodation",
    transport: "Transportation",
    documents: "Required Documents",
    cancellation: "Cancellation and Refund Terms",
    similarTours: "Similar Tours",
    duration: "Duration",
    route: "Route",
    startingPrice: "Starting price",
    departures: "Departure dates",
    priceNote: "Per person price based on double room accommodation.",
    form: {
      name: "Full Name",
      email: "Email",
      phone: "Phone",
      tour: "Tour of Interest",
      guests: "Number of Guests",
      date: "Preferred Date",
      notes: "Additional Notes",
      notesPlaceholder: "Room preference, special requests or questions",
      kvkk: "I consent to the processing of my personal data for communication purposes.",
      submit: "Submit",
      loading: "Sending...",
      success: "Your reservation request has been received. Our team will contact you as soon as possible.",
      chooseTour: "Select a tour",
      requiredName: "Full name is required.",
      requiredEmail: "Enter a valid email.",
      requiredPhone: "Enter a valid phone number.",
      requiredTour: "Select a tour.",
      requiredGuests: "Enter guest count.",
      requiredDate: "Select a date.",
      requiredKvkk: "Consent is required.",
    },
  },
  ar: {
    langLabel: "AR",
    dir: "rtl",
    nav: ["الرئيسية", "الجولات", "من نحن", "المدونة", "الأسئلة", "اتصل بنا"],
    reserve: "طلب حجز",
    discoverTours: "استكشف الجولات",
    details: "عرض التفاصيل",
    continue: "اقرأ المزيد",
    all: "الكل",
    filters: "الفلاتر",
    search: "ابحث عن جولة أو مدينة أو فئة",
    listed: "جولة معروضة",
    popularTours: "الجولات الشائعة",
    popularTitle: "المسارات الأكثر طلبا",
    popularText: "استكشف جولات مخططة بعناية مع مرشدين محترفين وتفاصيل مريحة.",
    why: "لماذا روتا نوفا؟",
    whyTitle: "نرافقك طوال الرحلة",
    destinations: "الوجهات",
    destinationTitle: "مدن تلهم رحلتك",
    how: "كيف نعمل؟",
    howTitle: "سافر في ثلاث خطوات",
    testimonials: "آراء الضيوف",
    testimonialsTitle: "تجارب حقيقية من مسافرين سعداء",
    blog: "المدونة",
    blogTitle: "أدلة التحضير للسفر",
    ctaTitle: "رحلتك القادمة تبدأ هنا.",
    ctaText: "لنخطط معا للجولة الأنسب لك.",
    contactNow: "تواصل الآن",
    heroTitle: "انطلق إلى وجهة أحلامك بثقة.",
    heroText: "اكتشف مع RotaNova Travel جولات لا تنسى من الثقافة والطبيعة إلى المدن الأوروبية والوجهات المميزة.",
    heroTrust: "عضوية TURSAB افتراضية · دفع آمن",
    stats: ["أكثر من 10 سنوات خبرة", "أكثر من 50 مسارا", "أكثر من 12,000 ضيف سعيد", "مرشدون محترفون"],
    whyCards: ["إرشاد احترافي", "مواصلات آمنة", "فنادق مختارة بعناية", "ميزة المجموعات الصغيرة", "دعم 24/7", "خيارات دفع مرنة"],
    whyCardText: "تواصل واضح وتخطيط آمن وتشغيل دقيق في كل مرحلة من رحلتك.",
    steps: ["اختر مسارك", "أرسل طلب الحجز", "جهز حقيبتك"],
    stepText: "يوضح فريقنا الخيارات ويكمل البرنامج الأنسب معك.",
    pageToursText: "صف رحلتك، قارن المسارات واترك طلبا للجولة الأنسب لك.",
    pageAboutText: "تأسست RotaNova Travel لتحويل السفر إلى تجربة منظمة وآمنة وملهمة.",
    pageBlogText: "أدلة عملية وواضحة ومفيدة قبل الانطلاق.",
    pageContactText: "أرسل أسئلتك وطلبات الجولات وخطط المجموعات الخاصة.",
    pageReservationText: "شارك بعض التفاصيل وسيعود فريقنا بالبرنامج وخيارات الدفع المناسبة.",
    pageFaqText: "إجابات عن الأسئلة الشائعة حول الحجز والدفع والتأشيرة والجولات.",
    tourSummary: "ملخص الجولة",
    itinerary: "البرنامج اليومي",
    included: "يشمل السعر",
    excluded: "لا يشمل السعر",
    accommodation: "معلومات الإقامة",
    transport: "معلومات المواصلات",
    documents: "الوثائق المطلوبة",
    cancellation: "شروط الإلغاء والاسترداد",
    similarTours: "جولات مشابهة",
    duration: "المدة",
    route: "المسار",
    startingPrice: "السعر يبدأ من",
    departures: "تواريخ الانطلاق",
    priceNote: "السعر للشخص في غرفة مزدوجة.",
    form: {
      name: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      tour: "الجولة المطلوبة",
      guests: "عدد الأشخاص",
      date: "التاريخ المفضل",
      notes: "ملاحظات إضافية",
      notesPlaceholder: "تفضيل الغرفة أو الطلبات الخاصة أو الأسئلة",
      kvkk: "أوافق على معالجة بياناتي الشخصية لأغراض التواصل.",
      submit: "إرسال",
      loading: "جار الإرسال...",
      success: "تم استلام طلب الحجز بنجاح. سيتواصل معك فريقنا في أقرب وقت.",
      chooseTour: "اختر جولة",
      requiredName: "الاسم الكامل مطلوب.",
      requiredEmail: "أدخل بريدا إلكترونيا صحيحا.",
      requiredPhone: "أدخل رقم هاتف صحيحا.",
      requiredTour: "اختر جولة.",
      requiredGuests: "أدخل عدد الأشخاص.",
      requiredDate: "اختر التاريخ.",
      requiredKvkk: "الموافقة مطلوبة.",
    },
  },
};

const localizedTours = {
  tr: [
    ["kapadokya-kultur-turu", "Kapadokya Kültür Turu", "Nevşehir, Türkiye", "Yurt İçi / Kültür", "2 Gece 3 Gün", "₺6.900", images.cappadocia, "Peri bacaları, sıcak hava balonları ve eşsiz vadilerle dolu büyüleyici bir Kapadokya deneyimi.", "Popüler", "Peri bacaları, yeraltı şehirleri ve gün doğumu manzaralarıyla kısa ama dolu dolu bir kültür kaçamağı.", ["1. Gün: İstanbul’dan Kapadokya’ya ulaşım, Göreme panoraması", "2. Gün: Paşabağ, Avanos, Uçhisar ve vadiler", "3. Gün: Balon seyir noktası, yeraltı şehri ve dönüş"], "Göreme, Avanos, Uçhisar", "12 Mayıs, 7 Haziran, 21 Temmuz"],
    ["italya-ruyasi-turu", "İtalya Rüyası Turu", "Roma, Floransa, Venedik, Milano", "Yurt Dışı / Kültür", "6 Gece 7 Gün", "899€", images.italy, "İtalya’nın tarihi şehirlerini, sanatını, mutfağını ve romantik atmosferini keşfedin.", "Sınırlı Kontenjan", "Roma’dan Milano’ya uzanan bu rota sanat, tarih, lezzet ve şehir yaşamını dengeli bir programla sunar.", ["1. Gün: İstanbul’dan Roma’ya uçuş, panoramik şehir turu", "2. Gün: Kolezyum, Roma Forumu, Trevi Çeşmesi", "3. Gün: Floransa’ya geçiş, Duomo ve Ponte Vecchio gezisi", "4. Gün: Pisa Kulesi ziyareti ve serbest zaman", "5. Gün: Venedik’e geçiş, San Marco Meydanı", "6. Gün: Milano şehir turu", "7. Gün: İstanbul’a dönüş"], "Roma, Floransa, Venedik, Milano", "12 Haziran, 5 Temmuz, 18 Ağustos"],
    ["karadeniz-yaylalari-turu", "Karadeniz Yaylaları Turu", "Trabzon, Rize, Artvin", "Yurt İçi / Doğa", "4 Gece 5 Gün", "₺12.500", images.blacksea, "Sisli yaylalar, ahşap evler, şelaleler ve doğayla iç içe unutulmaz bir rota.", "Yeni", "Doğayla iç içe, bol manzaralı ve yöresel lezzetlerle zenginleşen ferah bir yayla rotası.", ["1. Gün: Trabzon şehir turu ve Sümela Manastırı", "2. Gün: Uzungöl ve çevre yaylalar", "3. Gün: Ayder Yaylası ve Gelintülü Şelalesi", "4. Gün: Artvin, Borçka Karagöl ve serbest zaman", "5. Gün: Yöresel alışveriş ve dönüş"], "Trabzon, Rize, Artvin", "20 Mayıs, 14 Haziran, 9 Ağustos"],
    ["balkanlar-kesif-turu", "Balkanlar Keşif Turu", "Saraybosna, Belgrad, Üsküp, Ohrid", "Yurt Dışı / Kültür", "7 Gece 8 Gün", "749€", images.balkans, "Tarihi şehirler, Osmanlı mirası ve Balkan kültürünü bir arada yaşayacağınız kapsamlı tur.", "Popüler", "Balkan şehirlerinin tarihi dokusunu, çok kültürlü yaşamını ve sıcak misafirperverliğini keşfedin.", ["1. Gün: Saraybosna varış ve Başçarşı gezisi", "2. Gün: Mostar Köprüsü ve Blagay Tekkesi", "3. Gün: Belgrad panoramik şehir turu", "4. Gün: Üsküp’e geçiş ve Taşköprü", "5. Gün: Ohrid Gölü ve tarihi merkez", "6. Gün: Manastır ve serbest zaman", "7. Gün: Yerel pazarlar ve kültür rotası", "8. Gün: Dönüş"], "Saraybosna, Belgrad, Üsküp, Ohrid", "3 Haziran, 19 Temmuz, 2 Eylül"],
    ["ege-gastronomi-turu", "Ege Gastronomi Turu", "İzmir, Alaçatı, Urla, Ayvalık", "Yurt İçi / Gastronomi", "3 Gece 4 Gün", "₺9.800", images.aegean, "Ege’nin zeytinyağlıları, şarap bağları, sahil kasabaları ve yerel lezzetleriyle dolu özel rota.", "Lezzet Rotası", "Bağ rotaları, yerel üreticiler, sahil kasabaları ve Ege mutfağıyla keyifli bir lezzet deneyimi.", ["1. Gün: İzmir buluşma, Kemeraltı ve yerel tatlar", "2. Gün: Urla bağ rotası ve tadım deneyimi", "3. Gün: Alaçatı, Çeşme ve sahil lezzetleri", "4. Gün: Ayvalık, zeytinyağı atölyesi ve dönüş"], "İzmir, Urla, Alaçatı, Ayvalık", "10 Mayıs, 28 Haziran, 16 Ağustos"],
    ["paris-amsterdam-turu", "Paris & Amsterdam Turu", "Fransa, Hollanda", "Yurt Dışı / Şehir Turu", "5 Gece 6 Gün", "829€", images.paris, "Romantik Paris sokaklarından Amsterdam kanallarına uzanan keyifli Avrupa turu.", "Premium", "İki ikonik Avrupa şehrini müze, kanal, meydan ve serbest keşif dengesiyle yaşayın.", ["1. Gün: Paris varış ve panoramik şehir turu", "2. Gün: Louvre çevresi, Eiffel ve Seine", "3. Gün: Montmartre ve serbest zaman", "4. Gün: Amsterdam’a geçiş, kanal bölgesi", "5. Gün: Müze Meydanı, Dam ve serbest zaman", "6. Gün: Dönüş"], "Paris, Amsterdam", "8 Haziran, 22 Temmuz, 12 Eylül"],
  ],
  en: [
    ["kapadokya-kultur-turu", "Cappadocia Culture Tour", "Nevsehir, Turkey", "Domestic / Culture", "2 Nights 3 Days", "₺6,900", images.cappadocia, "A magical Cappadocia experience filled with fairy chimneys, hot air balloons and unique valleys.", "Popular", "A compact culture escape with fairy chimneys, underground cities and sunrise views.", ["Day 1: Travel to Cappadocia, Goreme panorama", "Day 2: Pasabag, Avanos, Uchisar and valleys", "Day 3: Balloon viewpoint, underground city and return"], "Goreme, Avanos, Uchisar", "May 12, June 7, July 21"],
    ["italya-ruyasi-turu", "Italy Dream Tour", "Rome, Florence, Venice, Milan", "International / Culture", "6 Nights 7 Days", "899€", images.italy, "Discover Italy’s historic cities, art, cuisine and romantic atmosphere.", "Limited Seats", "From Rome to Milan, this route blends art, history, food and city life in a balanced itinerary.", ["Day 1: Flight from Istanbul to Rome, panoramic city tour", "Day 2: Colosseum, Roman Forum, Trevi Fountain", "Day 3: Florence, Duomo and Ponte Vecchio", "Day 4: Pisa Tower visit and free time", "Day 5: Venice and St. Mark’s Square", "Day 6: Milan city tour", "Day 7: Return to Istanbul"], "Rome, Florence, Venice, Milan", "June 12, July 5, August 18"],
    ["karadeniz-yaylalari-turu", "Black Sea Highlands Tour", "Trabzon, Rize, Artvin", "Domestic / Nature", "4 Nights 5 Days", "₺12,500", images.blacksea, "Misty highlands, wooden houses, waterfalls and a memorable nature route.", "New", "A fresh mountain route full of views, local flavors and peaceful nature.", ["Day 1: Trabzon city tour and Sumela Monastery", "Day 2: Uzungol and nearby highlands", "Day 3: Ayder Highland and waterfall", "Day 4: Artvin and Borcka Karagol", "Day 5: Local shopping and return"], "Trabzon, Rize, Artvin", "May 20, June 14, August 9"],
    ["balkanlar-kesif-turu", "Balkans Discovery Tour", "Sarajevo, Belgrade, Skopje, Ohrid", "International / Culture", "7 Nights 8 Days", "749€", images.balkans, "A rich route through historic cities, Ottoman heritage and Balkan culture.", "Popular", "Discover the historic texture, multicultural life and warm hospitality of the Balkans.", ["Day 1: Sarajevo arrival and Bascarsija", "Day 2: Mostar Bridge and Blagaj", "Day 3: Belgrade panoramic tour", "Day 4: Skopje and Stone Bridge", "Day 5: Ohrid Lake and old town", "Day 6: Bitola and free time", "Day 7: Local markets and culture route", "Day 8: Return"], "Sarajevo, Belgrade, Skopje, Ohrid", "June 3, July 19, September 2"],
    ["ege-gastronomi-turu", "Aegean Gastronomy Tour", "Izmir, Alacati, Urla, Ayvalik", "Domestic / Gastronomy", "3 Nights 4 Days", "₺9,800", images.aegean, "A special route full of Aegean flavors, vineyards, coastal towns and local tastes.", "Food Route", "A delicious journey through vineyards, local producers, coastal towns and Aegean cuisine.", ["Day 1: Izmir meeting, Kemeralti and local flavors", "Day 2: Urla vineyards and tasting", "Day 3: Alacati, Cesme and coastal tastes", "Day 4: Ayvalik, olive oil workshop and return"], "Izmir, Urla, Alacati, Ayvalik", "May 10, June 28, August 16"],
    ["paris-amsterdam-turu", "Paris & Amsterdam Tour", "France, Netherlands", "International / City Tour", "5 Nights 6 Days", "829€", images.paris, "A delightful European tour from romantic Paris streets to Amsterdam canals.", "Premium", "Experience two iconic European cities with museums, canals, squares and free discovery time.", ["Day 1: Paris arrival and panoramic tour", "Day 2: Louvre area, Eiffel and Seine", "Day 3: Montmartre and free time", "Day 4: Transfer to Amsterdam and canals", "Day 5: Museum Square, Dam and free time", "Day 6: Return"], "Paris, Amsterdam", "June 8, July 22, September 12"],
  ],
  ar: [
    ["kapadokya-kultur-turu", "جولة كابادوكيا الثقافية", "نوشهر، تركيا", "داخلي / ثقافة", "ليلتان 3 أيام", "₺6,900", images.cappadocia, "تجربة ساحرة بين مداخن الجنيات والبالونات والوديان الفريدة.", "شائع", "رحلة ثقافية قصيرة وغنية بين المدن تحت الأرض ومشاهد الشروق.", ["اليوم 1: الوصول إلى كابادوكيا وجولة بانورامية في غوريمه", "اليوم 2: باشاباغ وأفانوس وأوتش حصار والوديان", "اليوم 3: نقطة مشاهدة البالونات والمدينة تحت الأرض والعودة"], "غوريمه، أفانوس، أوتش حصار", "12 مايو، 7 يونيو، 21 يوليو"],
    ["italya-ruyasi-turu", "جولة حلم إيطاليا", "روما، فلورنسا، البندقية، ميلانو", "خارجي / ثقافة", "6 ليال 7 أيام", "899€", images.italy, "اكتشف مدن إيطاليا التاريخية وفنها ومطبخها وأجواءها الرومانسية.", "مقاعد محدودة", "من روما إلى ميلانو، يجمع هذا المسار الفن والتاريخ والطعام والحياة المدنية.", ["اليوم 1: رحلة من إسطنبول إلى روما وجولة بانورامية", "اليوم 2: الكولوسيوم والمنتدى الروماني ونافورة تريفي", "اليوم 3: فلورنسا والدومو وبونتي فيكيو", "اليوم 4: زيارة برج بيزا ووقت حر", "اليوم 5: البندقية وساحة سان ماركو", "اليوم 6: جولة مدينة ميلانو", "اليوم 7: العودة إلى إسطنبول"], "روما، فلورنسا، البندقية، ميلانو", "12 يونيو، 5 يوليو، 18 أغسطس"],
    ["karadeniz-yaylalari-turu", "جولة مرتفعات البحر الأسود", "طرابزون، ريزه، أرتفين", "داخلي / طبيعة", "4 ليال 5 أيام", "₺12,500", images.blacksea, "مرتفعات ضبابية وبيوت خشبية وشلالات ومسار طبيعي لا ينسى.", "جديد", "مسار جبلي منعش مليء بالمناظر والنكهات المحلية والطبيعة الهادئة.", ["اليوم 1: جولة طرابزون ودير سوميلا", "اليوم 2: أوزونغول والمرتفعات القريبة", "اليوم 3: مرتفع آيدر والشلال", "اليوم 4: أرتفين وبورشكا كاراغول", "اليوم 5: تسوق محلي والعودة"], "طرابزون، ريزه، أرتفين", "20 مايو، 14 يونيو، 9 أغسطس"],
    ["balkanlar-kesif-turu", "جولة استكشاف البلقان", "سراييفو، بلغراد، سكوبيه، أوهريد", "خارجي / ثقافة", "7 ليال 8 أيام", "749€", images.balkans, "مسار شامل يجمع المدن التاريخية والإرث العثماني وثقافة البلقان.", "شائع", "اكتشف الطابع التاريخي والحياة متعددة الثقافات ودفء الضيافة في البلقان.", ["اليوم 1: الوصول إلى سراييفو وباشجارشيا", "اليوم 2: جسر موستار وبلاغاي", "اليوم 3: جولة بانورامية في بلغراد", "اليوم 4: سكوبيه والجسر الحجري", "اليوم 5: بحيرة أوهريد والمدينة القديمة", "اليوم 6: بيتولا ووقت حر", "اليوم 7: أسواق محلية ومسار ثقافي", "اليوم 8: العودة"], "سراييفو، بلغراد، سكوبيه، أوهريد", "3 يونيو، 19 يوليو، 2 سبتمبر"],
    ["ege-gastronomi-turu", "جولة مذاقات إيجه", "إزمير، ألاكاتي، أورلا، أيفاليك", "داخلي / طعام", "3 ليال 4 أيام", "₺9,800", images.aegean, "مسار خاص مليء بنكهات إيجه وكروم العنب والبلدات الساحلية.", "مسار النكهات", "رحلة شهية بين الكروم والمنتجين المحليين والبلدات الساحلية ومطبخ إيجه.", ["اليوم 1: لقاء في إزمير وكمر ألتي والنكهات المحلية", "اليوم 2: كروم أورلا وتجربة تذوق", "اليوم 3: ألاكاتي وتشيشمه ونكهات الساحل", "اليوم 4: أيفاليك وورشة زيت الزيتون والعودة"], "إزمير، أورلا، ألاكاتي، أيفاليك", "10 مايو، 28 يونيو، 16 أغسطس"],
    ["paris-amsterdam-turu", "جولة باريس وأمستردام", "فرنسا، هولندا", "خارجي / جولة مدن", "5 ليال 6 أيام", "829€", images.paris, "جولة أوروبية ممتعة من شوارع باريس الرومانسية إلى قنوات أمستردام.", "فاخر", "اختبر مدينتين أوروبيتين شهيرتين مع المتاحف والقنوات والساحات ووقت حر.", ["اليوم 1: الوصول إلى باريس وجولة بانورامية", "اليوم 2: محيط اللوفر وبرج إيفل ونهر السين", "اليوم 3: مونمارتر ووقت حر", "اليوم 4: الانتقال إلى أمستردام والقنوات", "اليوم 5: ساحة المتاحف ودام ووقت حر", "اليوم 6: العودة"], "باريس، أمستردام", "8 يونيو، 22 يوليو، 12 سبتمبر"],
  ],
};

export function getTours(lang) {
  return localizedTours[lang].map(([slug, title, location, category, duration, price, image, description, badge, summary, itinerary, route, departures], index) => ({
    id: index + 1,
    slug,
    title,
    location,
    category,
    duration,
    price,
    image,
    description,
    badge,
    summary,
    itinerary,
    route,
    departures,
    ...commonTourDetails[lang],
  }));
}

export function getContent(lang) {
  const d = dictionary[lang];
  const tours = getTours(lang);
  return {
    d,
    tours,
    destinations: [
      [tours[0].title.split(" ")[0], images.cappadocia],
      ["Roma", images.italy],
      ["Paris", images.paris],
      ["Amsterdam", images.amsterdam],
      ["Saraybosna", images.balkans],
      ["Trabzon", images.blacksea],
      ["Santorini", images.santorini],
      ["Barselona", images.barcelona],
    ].map(([name, image]) => ({ name, image })),
    testimonials: {
      tr: [
        ["Ece Yılmaz", "İtalya Rüyası Turu", "İtalya turu beklentimizin çok üstündeydi. Rehberimiz çok bilgiliydi, oteller merkeziydi ve program çok iyi planlanmıştı."],
        ["Burak Acar", "Karadeniz Yaylaları Turu", "Ailemle çok rahat ettik. Transferler zamanında, yayla programı dengeli ve iletişim her an çok hızlıydı."],
        ["Derya & Can", "Ege Gastronomi Turu", "Küçük grup olması deneyimi çok özel yaptı. Mekan seçimleri ve yerel üretici ziyaretleri çok keyifliydi."],
      ],
      en: [
        ["Ece Yilmaz", "Italy Dream Tour", "The Italy tour was far beyond our expectations. Our guide was knowledgeable, hotels were central and the program was very well planned."],
        ["Burak Acar", "Black Sea Highlands Tour", "My family felt very comfortable. Transfers were on time, the highland program was balanced and communication was quick."],
        ["Derya & Can", "Aegean Gastronomy Tour", "The small group made the experience special. Venue choices and local producer visits were delightful."],
      ],
      ar: [
        ["إيجه يلماز", "جولة حلم إيطاليا", "كانت جولة إيطاليا أعلى من توقعاتنا. المرشد كان متمكنا والفنادق مركزية والبرنامج منظم جدا."],
        ["بوراك أجار", "جولة مرتفعات البحر الأسود", "شعرت عائلتي براحة كبيرة. التنقلات في الوقت المحدد والبرنامج متوازن والتواصل سريع."],
        ["دريا وجان", "جولة مذاقات إيجه", "المجموعة الصغيرة جعلت التجربة خاصة، واختيارات الأماكن وزيارات المنتجين المحليين كانت رائعة."],
      ],
    }[lang].map(([name, tour, text]) => ({ name, tour, text, rating: 5 })),
    blogPosts: {
      tr: [
        ["İlk Kez Yurt Dışına Çıkacaklara Tavsiyeler", "Seyahat Rehberi", "3 Mayıs 2026", images.blog, "Pasaport, vize, havalimanı ve valiz hazırlığında işinizi kolaylaştıracak pratik öneriler."],
        ["Kapadokya’da Görülmesi Gereken 7 Yer", "Destinasyon", "24 Nisan 2026", images.cappadocia, "Vadilerden gün doğumu noktalarına Kapadokya deneyimini zenginleştiren duraklar."],
        ["Avrupa Turu İçin Bavul Hazırlama Rehberi", "Bavul Hazırlığı", "12 Nisan 2026", images.luggage, "Çok şehirli Avrupa rotalarında hafif, düzenli ve eksiksiz valiz hazırlamanın yolları."],
        ["Schengen Vizesi İçin Evrak Kontrol Listesi", "Vize & Evrak", "4 Nisan 2026", images.papers, "Başvuru sürecinde sık istenen belgeler ve dikkat edilmesi gereken temel noktalar."],
        ["Roma’da Ne Yenir?", "Yeme İçme", "18 Mart 2026", images.food, "Klasik makarnalardan sokak lezzetlerine Roma sofralarında öne çıkan tatlar."],
      ],
      en: [
        ["Tips for First-Time International Travelers", "Travel Guide", "May 3, 2026", images.blog, "Practical tips for passport, visa, airport and luggage preparation."],
        ["7 Places to See in Cappadocia", "Destination", "April 24, 2026", images.cappadocia, "Stops that enrich your Cappadocia experience from valleys to sunrise points."],
        ["Packing Guide for a Europe Tour", "Packing", "April 12, 2026", images.luggage, "How to pack light, organized and complete for multi-city Europe routes."],
        ["Schengen Visa Document Checklist", "Visa & Documents", "April 4, 2026", images.papers, "Commonly requested documents and key points for your application."],
        ["What to Eat in Rome?", "Food & Drink", "March 18, 2026", images.food, "From classic pasta to street food, flavors that stand out in Rome."],
      ],
      ar: [
        ["نصائح للمسافرين إلى الخارج لأول مرة", "دليل السفر", "3 مايو 2026", images.blog, "نصائح عملية للجواز والتأشيرة والمطار وتحضير الحقيبة."],
        ["7 أماكن يجب رؤيتها في كابادوكيا", "وجهة", "24 أبريل 2026", images.cappadocia, "محطات تثري تجربة كابادوكيا من الوديان إلى نقاط الشروق."],
        ["دليل تجهيز الحقيبة لجولة أوروبا", "تجهيز الحقيبة", "12 أبريل 2026", images.luggage, "طريقة تجهيز حقيبة خفيفة ومنظمة لمسارات أوروبا متعددة المدن."],
        ["قائمة وثائق تأشيرة شنغن", "تأشيرة ووثائق", "4 أبريل 2026", images.papers, "الوثائق المطلوبة كثيرا والنقاط المهمة في طلب التأشيرة."],
        ["ماذا تأكل في روما؟", "طعام وشراب", "18 مارس 2026", images.food, "من الباستا الكلاسيكية إلى أطعمة الشارع، نكهات روما المميزة."],
      ],
    }[lang].map(([title, category, date, image, excerpt]) => ({ title, category, date, image, excerpt })),
    faqs: {
      tr: [
        ["Tura nasıl rezervasyon yapabilirim?", "Tur sayfasından veya rezervasyon formundan talep bırakabilirsiniz. Ekibimiz müsaitlik ve ödeme bilgileriyle size dönüş yapar."],
        ["Ödeme seçenekleri nelerdir?", "Kredi kartı, havale/EFT ve dönemsel taksit seçenekleri sunuyoruz. Tur bazında ödeme planı değişebilir."],
        ["Vize işlemlerinde yardımcı oluyor musunuz?", "Evet. Evrak listesi, randevu yönlendirmesi ve süreç takibi konusunda danışmanlık sağlıyoruz."],
        ["Tur iptal olursa ne olur?", "Operasyon kaynaklı iptallerde alternatif tarih, farklı tur veya iade seçenekleri sunulur."],
        ["Çocuklar için indirim var mı?", "Yaş aralığına, oda tipine ve ulaşım koşullarına göre çocuk indirimleri uygulanabilir."],
        ["Turlarda rehberlik hizmeti var mı?", "Programlarımızda profesyonel rehberlik hizmeti bulunur."],
        ["Tek kişi katılabilir miyim?", "Elbette. Tek kişilik oda farkı veya uygun oda paylaşım seçenekleri için ekibimiz sizi bilgilendirir."],
        ["Seyahat sigortası dahil mi?", "Bazı turlarda dahildir, bazılarında ek hizmet olarak sunulur. Detaylar tur sayfasında belirtilir."],
      ],
      en: [
        ["How can I book a tour?", "You can leave a request from the tour page or reservation form. Our team returns with availability and payment details."],
        ["What payment options are available?", "We offer credit card, bank transfer and seasonal installment options. Payment plans may vary by tour."],
        ["Do you help with visa procedures?", "Yes. We provide guidance for document lists, appointments and process tracking."],
        ["What happens if a tour is cancelled?", "We offer alternative dates, another tour or refund options for operational cancellations."],
        ["Are there discounts for children?", "Child discounts may apply depending on age, room type and transportation terms."],
        ["Is guiding service included?", "Our programs include professional guiding service."],
        ["Can I join alone?", "Yes. Our team informs you about single room supplement or room sharing options."],
        ["Is travel insurance included?", "It is included in some tours and offered as an extra service in others. Details are listed on each tour page."],
      ],
      ar: [
        ["كيف يمكنني حجز جولة؟", "يمكنك إرسال طلب من صفحة الجولة أو نموذج الحجز، وسيعود فريقنا بتفاصيل التوفر والدفع."],
        ["ما خيارات الدفع؟", "نوفر الدفع بالبطاقة والتحويل وخيارات تقسيط موسمية، وقد تختلف الخطة حسب الجولة."],
        ["هل تساعدون في إجراءات التأشيرة؟", "نعم، نقدم إرشادا لقائمة الوثائق والمواعيد ومتابعة العملية."],
        ["ماذا يحدث إذا ألغيت الجولة؟", "في حالات الإلغاء التشغيلية نقدم تاريخا بديلا أو جولة أخرى أو خيارات استرداد."],
        ["هل يوجد خصم للأطفال؟", "قد تطبق خصومات حسب العمر ونوع الغرفة وشروط النقل."],
        ["هل تشمل الجولات خدمة الإرشاد؟", "نعم، تشمل برامجنا خدمة إرشاد احترافية."],
        ["هل يمكنني الانضمام وحدي؟", "بالطبع، يوضح فريقنا فرق الغرفة الفردية أو خيارات مشاركة الغرفة."],
        ["هل يشمل السعر تأمين السفر؟", "يشمل بعض الجولات ويقدم كخدمة إضافية في أخرى، وتظهر التفاصيل في صفحة الجولة."],
      ],
    }[lang].map(([question, answer]) => ({ question, answer })),
    heroImage: images.hero,
    aboutImage: images.about,
  };
}
